// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDkYt2_ZR_w6d0y9X49Hp7ZhX_Czroj0_c",
      authDomain: "app-livros-322be.firebaseapp.com",
      projectId: "app-livros-322be",
      storageBucket: "app-livros-322be.firebasestorage.app",
      messagingSenderId: "1012183596405",
      appId: "1:1012183596405:web:40a0072b92662b5c4e673c",
      measurementId: "G-ZX60XZDFZV");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtiBZx5gtdeb389vlCC1eTn_UlMYPv2bc',
    appId: '1:1012183596405:ios:3429b6782db9c9224e673c',
    messagingSenderId: '1012183596405',
    projectId: 'app-livros-322be',
    storageBucket: 'app-livros-322be.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvL9EetEZYZ5Z--94xJZr0B45Vl1hY-To',
    appId: '1:357443021886:web:598c94180331ece96af56f',
    messagingSenderId: '357443021886',
    projectId: 'app-livros-322be',
    authDomain: 'app-livros-322be.firebaseapp.com',
    storageBucket: 'app-livros-322be.firebasestorage.app',
    measurementId: 'G-3WCJKDMESB',
  );
}
